apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - name: web
    port: {{ .Values.port }}
    targetPort: 8080
    nodePort: 31000
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort