name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t baofci/reactjs:${{ env.TAG }} .
          docker push baofci/reactjs:${{ env.TAG }}

      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: BaoICTHustK67/web_values
          token: ${{ secrets.GITHUB_TOKEN }}
          path: .

      - name: Update image version in values.yaml
        run: |
          sed -i "s/^  tag: .*/  tag: ${{ env.TAG }}/" ./values.yaml

      - name: Commit and push changes
        run: |
          cd .
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'bachdtm169@gmail.com'
          git add values.yaml
          git commit -m "Update image version to ${{ env.TAG }}"
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
